// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isArray(prim) {
  return Array.isArray(prim);
}

function classify(arrayable) {
  if (Array.isArray(arrayable)) {
    return {
            TAG: /* Array */1,
            _0: arrayable
          };
  } else {
    return {
            TAG: /* Single */0,
            _0: arrayable
          };
  }
}

var Arrayable = {
  isArray: isArray,
  classify: classify
};

var Mutable = {};

function classify$1(definition) {
  if (typeof definition === "boolean") {
    return {
            TAG: /* Boolean */1,
            _0: definition
          };
  } else {
    return {
            TAG: /* Schema */0,
            _0: definition
          };
  }
}

var Definition = {
  classify: classify$1
};

function classify$2(dependency) {
  if (Array.isArray(dependency)) {
    return {
            TAG: /* Required */1,
            _0: dependency
          };
  } else {
    return {
            TAG: /* Schema */0,
            _0: dependency
          };
  }
}

var Dependency = {
  classify: classify$2
};

exports.Arrayable = Arrayable;
exports.Mutable = Mutable;
exports.Definition = Definition;
exports.Dependency = Dependency;
/* No side effect */
