// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function classify(arrayable) {
  if (Array.isArray(arrayable)) {
    return {
            TAG: "Array",
            _0: arrayable
          };
  } else {
    return {
            TAG: "Single",
            _0: arrayable
          };
  }
}

var Arrayable = {
  classify: classify
};

var Mutable = {};

function classify$1(definition) {
  if (typeof definition === "boolean") {
    return {
            TAG: "Boolean",
            _0: definition
          };
  } else {
    return {
            TAG: "Schema",
            _0: definition
          };
  }
}

var Definition = {
  classify: classify$1
};

var Dependency = {};

exports.Arrayable = Arrayable;
exports.Mutable = Mutable;
exports.Definition = Definition;
exports.Dependency = Dependency;
/* No side effect */
