// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as JSONSchema from "../src/JSONSchema.res.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";

Ava("Regression test", (function (t) {
        var jsonSchema = {
          $schema: "http://json-schema.org/draft-07/schema#",
          type: "object",
          properties: {
            page: {
              type: "number",
              minimum: 1,
              default: 1
            },
            limit: {
              type: "number",
              minimum: 1,
              default: 100
            }
          },
          additionalProperties: false
        };
        t.deepEqual(S$RescriptSchema.inline(JSONSchema.toRescriptSchema(jsonSchema)), "S.object(s =>\n  {\n    \"page\": s.field(\"page\", S.option(S.float->S.floatMin(1., ~message=\"Number must be greater than or equal to 1\"))->S.Option.getOr(%raw(\`1\`))),\n    \"limit\": s.field(\"limit\", S.option(S.float->S.floatMin(1., ~message=\"Number must be greater than or equal to 1\"))->S.Option.getOr(%raw(\`100\`))),\n  }\n)->S.strict");
      }));

export {
  
}
/*  Not a pure module */
